// Generated by gentokens.rkt
#pragma once
namespace parser {
  enum class Tok {
    TInvalid,
    TWhitespace,
    TLinebreak,
    TIdent,
    TDefn,
    TIf,
    TElse,
    TLet,
    TIn,
    TInt,
    TFloat,
    TStr,
    TParOpen,
    TParClose,
    TBrOpen,
    TBrClose,
    TComma,
    TColon,
    TPlaceholder,
    TNe,
    TEq2,
    TEq,
    TLt,
    TGt,
    TLe,
    TGe,
    TOr1,
    TOr2,
    TAnd1,
    TAnd2,
    TShLeft,
    TShRight,
    TAdd,
    TSub,
    TMul,
    TDiv,
    TRem,
  };
}

#define TOKEN_PATTERNS {\
  {parser::Tok::TWhitespace, "[ \\t\\v\\f\\r]+"},\
  {parser::Tok::TLinebreak, "[ \\t\\v\\f\\r]*\\n"},\
  {parser::Tok::TIdent, "[a-zA-Z_][a-zA-Z_0-9]*"},\
  {parser::Tok::TDefn, "defn"},\
  {parser::Tok::TIf, "if"},\
  {parser::Tok::TElse, "else"},\
  {parser::Tok::TLet, "let"},\
  {parser::Tok::TIn, "in"},\
  {parser::Tok::TInt, "0|[1-9][0-9]*"},\
  {parser::Tok::TFloat, "[0-9]+\\.[0-9]+"},\
  {parser::Tok::TStr, "\"([^\"\\\\]|\\\\[\"\\\\])*\""},\
  {parser::Tok::TParOpen, "\\("},\
  {parser::Tok::TParClose, "\\)"},\
  {parser::Tok::TBrOpen, "\\{"},\
  {parser::Tok::TBrClose, "\\}"},\
  {parser::Tok::TComma, ","},\
  {parser::Tok::TColon, ":"},\
  {parser::Tok::TPlaceholder, "_"},\
  {parser::Tok::TNe, "!="},\
  {parser::Tok::TEq2, "=="},\
  {parser::Tok::TEq, "="},\
  {parser::Tok::TLt, "<"},\
  {parser::Tok::TGt, ">"},\
  {parser::Tok::TLe, "<="},\
  {parser::Tok::TGe, ">="},\
  {parser::Tok::TOr1, "\\|"},\
  {parser::Tok::TOr2, "\\|\\|"},\
  {parser::Tok::TAnd1, "&"},\
  {parser::Tok::TAnd2, "&&"},\
  {parser::Tok::TShLeft, "<<"},\
  {parser::Tok::TShRight, ">>"},\
  {parser::Tok::TAdd, "\\+"},\
  {parser::Tok::TSub, "-"},\
  {parser::Tok::TMul, "\\*"},\
  {parser::Tok::TDiv, "/"},\
  {parser::Tok::TRem, "%"},\
}
