#!/bin/bash

FULL=$(basename "$1")
BASE=$(basename "$1" .crp)

export CRP_FILENAME
CRP_FILENAME=$FULL
export CRP_FILEDIR
CRP_FILEDIR=$(readlink -f "$(dirname "$1")")

./bin/in2llvm < "$1" > "$BASE.ll" &&
llc "$BASE.ll" &&
as -ad "$BASE.s" -o "$BASE.o" &&
cc --static "$BASE.o" -L. -lcrp -o "$BASE"
