#!/bin/bash

if [ $# -lt 1 ]; then
    echo 1>&2 "Usage: $0 <file> [[-o <opt arg>] | [-c <lcc arg>] | [-a <as arg>] | [-l <cc arg>] ...]"
    exit 2
fi

FILE="$1"
shift
while getopts "o:c:a:l:" o; do
    case "${o}" in
        o) OPT_ARGS="$OPT_ARGS ${OPTARG}";;
        c) LCC_ARGS="$LCC_ARGS ${OPTARG}";;
        a) AS_ARGS="$AS_ARGS ${OPTARG}";;
        l) CC_ARGS="$CC_ARGS ${OPTARG}";;
    esac
done

if [ "$FILE" == "--" ]; then
    FILE="/dev/stdin"
    FULL="stdin.crp"
    BASE="a.out"
    DIR=$(pwd)
else
    FULL=$(basename "$FILE")
    BASE=$(basename "$FILE" .crp)
    DIR=$(readlink -f "$(dirname "FILE")")
fi

export CRP_FILENAME
CRP_FILENAME="$FULL"
export CRP_FILEDIR
CRP_FILEDIR="$DIR"

TRAP_SIGS="0 1 2 3 15"
obj_file="$(mktemp --suffix ".o")"
trap "rm -f $obj_file" $TRAP_SIGS
ll_file="$(mktemp --suffix ".ll")"
trap "rm -f $ll_file" $TRAP_SIGS
opt_ll_file="$(mktemp --suffix ".ll")"
trap "rm -f $opt_ll_file" $TRAP_SIGS
asm_file="$(mktemp --suffix ".s")"
trap "rm -f $asm_file" $TRAP_SIGS

chirp2llvm < "$FILE" > "$ll_file" &&
    opt "$ll_file" $OPT_ARGS -o "$opt_ll_file" &&
    llc "$opt_ll_file" $LCC_ARGS -relocation-model=pic -o "$asm_file" &&
    as "$asm_file" $AS_ARGS -ad -o "$obj_file" &&
    cc "$obj_file" $CC_ARGS -L. -lchirp_runtime -o "$BASE"
