#!/bin/bash

if [ $# -lt 1 ]; then
    echo 1>&2 "Usage: $0 <file> [[-o <opt arg>] | [-c <lcc arg>] | [-a <as arg>] | [-l <cc arg>] ...]"
    exit 2
fi

FILE="$1"
shift
while getopts "o:c:a:l:" o; do
    case "${o}" in
        o) OPT_ARGS="$OPT_ARGS ${OPTARG}";;
        c) LCC_ARGS="$LCC_ARGS ${OPTARG}";;
        a) AS_ARGS="$AS_ARGS ${OPTARG}";;
        l) CC_ARGS="$CC_ARGS ${OPTARG}";;
    esac
done

if [ "$FILE" == "--" ]; then
    FILE="/dev/stdin"
    FULL="stdin.crp"
    BASE="stdin"
    OUT="a.out"
    DIR=$(pwd)
else
    FULL=$(basename "$FILE")
    BASE=$(basename "$FILE" .crp)
    OUT="$BASE"
    DIR=$(readlink -f "$(dirname "$FILE")")
fi

export CRP_FILENAME
CRP_FILENAME="$FULL"
export CRP_FILEDIR
CRP_FILEDIR="$DIR"

TMPDIR="$(mktemp --dir --tmpdir $(date +"crpc.%Y-%m-%d.%H:%M:%S.XXX"))"
ll_file="$TMPDIR/$BASE.ll"
opt_ll_file="$TMPDIR/$BASE.opt.ll"
obj_file="$TMPDIR/$BASE.o"
asm_file="$TMPDIR/$BASE.s"

chirp2llvm < "$FILE" > "$ll_file" &&
    opt "$ll_file" $OPT_ARGS -o "$opt_ll_file" &&
    llc "$opt_ll_file" $LCC_ARGS -relocation-model=pic -o "$asm_file" &&
    as "$asm_file" $AS_ARGS -ad -o "$obj_file" &&
    cc "$obj_file" $CC_ARGS -lchirp_runtime -o "$OUT" &&
    rm -rf $TMPDIR
