#!/usr/bin/env racket

#lang racket

(let loop
    ([line (read-line)]
     [enum '()]
     [res '()])
  (cond
    [(eof-object? line)
     (displayln "// Generated by gentokens.rkt")
     (displayln "#pragma once")
     (displayln "namespace parser {")
     (displayln "enum class Tok {")
     (displayln "TInvalid,")
     (displayln (string-join (reverse enum) "\n"))
     (displayln "};")
     (displayln "}")
     (newline)
     (displayln "#define TOKEN_PATTERNS {\\")
     (displayln (string-join (reverse res) "\n"))
     (displayln "}")]
    [(zero? (string-length line))
     (loop (read-line) enum res)]
    [else
     (loop
      (read-line)
      (cons (regexp-replace #px"(.+) ::= .+"
                            line
                            "\\1,")
            enum)
      (cons (regexp-replace #px"(.+) ::= ([/'])(.+)[/']"
                            line
                            (lambda (full name delim expr)
                              (format "  {parser::Tok::~a, ~s},\\"
                                      name
                                      (if (string=? delim "/")
                                          expr
                                          (regexp-quote expr)))))
            res))]))
