name: CMake

on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  LLVM_VERSION: 12.0.0

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        running-on: [ubuntu-latest, macos-10.15]
    runs-on: ${{matrix.running-on}}

    steps:
    - name: Install LLVM
      uses: KyleMayes/install-llvm-action@v1.5.0
      with:
        version: ${{env.LLVM_VERSION}}

    - name: Checkout Chirp
      uses: actions/checkout@v2
      with:
        path: chirp

    - name: Build Chirp
      run: |
        cmake -B ${{github.workspace}}/chirp/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=targets ${{github.workspace}}/chirp/src
        cmake --build ${{github.workspace}}/chirp/build
