name: CMake

on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  LLVM_VERSION: 12.0

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        running-on: [ubuntu-latest, macos-10.15, windows-latest]
    runs-on: ${{matrix.running-on}}

    steps:
    - uses: actions/checkout@v2
  
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1.4.1
      with:
        directory: ./llvm
        version: ${{env.LLVM_VERSION}}

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=targets src

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
