name: CMake

on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        running-on: [ubuntu-latest, macos-10.15, windows-latest]
    runs-on: ${{matrix.running-on}}

    steps:
    - name: Install LLVM (Unix)
      if: matrix.running-on != 'windows-latest'
      uses: KyleMayes/install-llvm-action@v1.5.0
      with:
        version: "12.0.0"

    - name: Install LLVM (Windows)
      if: matrix.running-on == 'windows-latest'
      run: |
        set FULL_DESC="llvm-12.0.1-windows-amd64-msvc15-msvcrt"
        Invoke-WebRequest -OutFile llvm.7z -Uri "https://github.com/vovkos/llvm-package-windows/releases/download/llvm-12.0.1/%FULL_DESC%.7z"
        7z x llvm.7z -ollvm-ex
        setx LLVM_DIR "${{github.workspace}}\\llvm-ex\\%FULL_DESC%"

    - name: Checkout Chirp
      uses: actions/checkout@v2
      with:
        path: chirp

    - name: Build Chirp
      run: |
        cmake -B ${{github.workspace}}/chirp/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=targets ${{github.workspace}}/chirp/src
        cmake --build ${{github.workspace}}/chirp/build
