name: CMake

on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  LLVM_VERSION: 12.0.0

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        running-on: [ubuntu-latest, macos-10.15, windows-latest]
    runs-on: ${{matrix.running-on}}

    steps:
    - name: Install LLVM
      if: matrix.running-on != 'windows-latest'
      uses: KyleMayes/install-llvm-action@v1.5.0
      with:
        version: ${{env.LLVM_VERSION}}

    - name: Cache LLVM
      if: matrix.running-on == 'windows-latest'
      uses: actions/cache@v2.1.6
      with:
        path: C:\Program Files\LLVM
        key: llvm-${{env.LLVM_VERSION}}

    - name: Checkout LLVM
      if: matrix.running-on == 'windows-latest' && steps.cache-llvm.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: llvm/llvm-project
        ref: llvmorg-${{env.LLVM_VERSION}}
        path: llvm

    - name: Build LLVM
      if: matrix.running-on == 'windows-latest' && steps.cache-llvm.outputs.cache-hit != 'true'
      run: |
        cmake -B ${{github.workspace}}/llvm/llvm/build -DCMAKE_BUILD_TYPE=Release ${{github.workspace}}/llvm/llvm/
        cmake --build ${{github.workspace}}/llvm/llvm/build
        cmake --build ${{github.workspace}}/llvm/llvm/build --target install

    - name: Checkout Chirp
      uses: actions/checkout@v2
      with:
        path: chirp

    - name: Build Chirp
      run: |
        cmake -B ${{github.workspace}}/chirp/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=targets ${{github.workspace}}/chirp/src
        cmake --build ${{github.workspace}}/chirp/build
