name: CMake

on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  LLVM_VERSION: 12.0.0

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        running-on: [ubuntu-latest, macos-10.15, windows-latest]
    runs-on: ${{matrix.running-on}}

    steps:
    - name: Install LLVM
      if: matrix.running-on != 'windows-latest'
      uses: eutro/install-llvm-action@82c57a1e923a6b5847bde9b5f46321b9efc89db5
      with:
        version: ${{env.LLVM_VERSION}}

    - name: Install LLVM (Windows)
      if: matrix.running-on == 'windows-latest'
      uses: eutro/install-llvm-action@82c57a1e923a6b5847bde9b5f46321b9efc89db5
      with:
        version: ${{env.LLVM_VERSION}}
        directory: ./llvm
        url: "https://github.com/vovkos/llvm-package-windows/releases/download/llvm-${version}/llvm-${version}-windows-amd64-msvc15-msvcrt.7z"

    - name: Checkout Chirp
      uses: actions/checkout@v2
      with:
        path: chirp

    - name: Build Chirp
      run: |
        cmake -B ${{github.workspace}}/chirp/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=targets ${{github.workspace}}/chirp/src
        cmake --build ${{github.workspace}}/chirp/build
